### ISSUE TITLE
Document unlocking without an key, by just using password

### ISSUE THREAD

**Issue by memegauste** [ceremcem/unlock-luks-partition#10]
As title says ;)

**Comment by ceremcem** [comment]
You mean "login with a password instead of an SSH key in order to unlock the disk", right?

**Comment by memegauste** [comment]
> You mean "login with a password instead of an SSH key in order to unlock the disk", right?

Yeah, I tried todo that and I am not sure if it's possible, implemented etc.
Seems that not writing `-s` flag in `DROPBEAR_OPTIONS` in dropbear config do not change anything.

**Comment by ghost** [comment]
yeah i need it

**Comment by ceremcem** [comment]
Here `you` want to connect to your `target` by ssh and use a password to unlock its LUKS layer. I think you need to suppress the public key checking, so your `target` will let `you` to connect without checking `your` public key. There is no way around. 

This, however, obviously introduces a MITM attack vulnerability, so it's outside the scope of this documentation. I'm going to close the issue, but we can continue talking about your particular necessity.

**Comment by ceremcem** [comment]
Disabling the public key checking effectively means replacing the Dropbear with a simple `nc` command and redirect the unencrypted password to the `cryptsetup`.
