### ISSUE TITLE
Strict host key checking must be disabled

### ISSUE THREAD

**Issue by ceremcem** [ceremcem/unlock-luks-partition#4]
To enable a second step flexibility, strict host key checking must be disabled so that the target node will be able to connect to another (possibly an untrusted) server which will forward the connections to our server. 

Since the server already has its encryption layer, there is no possible vulnerability introduced.

**Comment by ceremcem** [comment]
[Already disabled](https://github.com/ceremcem/unlock-luks-partition/blame/master/reverse-tunnel-setup.md#L107) with `-y -y` option.

**Comment by ralienpp** [comment]
@ceremcem, what is the role of duplicating the `-y` parameter? The documentation for https://linux.die.net/man/1/dbclient doesn't mention any effects for this case. Is this written twice on purpose?

**Comment by ceremcem** [comment]
This can't be a typo, I think I added `-y` twice on purpose. However you are also right. I can neither remember nor find again why I might have added this switch twice. 

This issue can be closed after verifying that the single `-y` switch works as expected.

**Comment by ralienpp** [comment]
It works with a single `-y` (tested on 2 Debian 11 systems).

**Comment by ceremcem** [comment]
Thanks for testing. I'd accept the PR for this if you open one.
