### ISSUE TITLE
link-with-server causes infinite loop if no internet connection is available

### ISSUE THREAD

**Issue by ceremcem** [ceremcem/unlock-luks-partition#7]
![image](https://user-images.githubusercontent.com/6639874/57926336-a9842680-78b3-11e9-8326-1e8290234768.png)

**Comment by j0h** [comment]
Hi @ceremcem, were you able to figure out what the issue might?

**Comment by ceremcem** [comment]
Sorry, but no. AFAIR, the case is valid only when you don't plug the ethernet cable to the machine so it was not a blocker issue in my case. 

If you can tell how you reproduce the issue (your setup and scenario) we can figure something out.

**Comment by j0h** [comment]
I'm using Ubuntu 18.04.2 LTS (Server) and after setting up dropbear-intiramfs, I pretty much followed the reverse tunnel instructions and faced the issues. What's your setup?

**Comment by ceremcem** [comment]
I'm using Debian 9 so there should be minor or no differences. Can you verify that you have an active internet connection on your `client` (Ubuntu 18.04.2 LTS (Server))? 

(I'm sorry that I don't have a hardware to reproduce this issue at the moment. I'll try to get one in the meanwhile.)

**Comment by j0h** [comment]
I'm going to try and replicate this through VirtualBox as it's going to be easier to debug. I'm testing with both with and without an active internet connection so that it works for both cases. Will report back when I get around to setting this up.

**Comment by ceremcem** [comment]
FYI: I can reproduce the same issue with a new hardware. I'm on it.

**Comment by ceremcem** [comment]
Reproduction: 

* [Create a VirtualBox machine with the real disk](https://superuser.com/a/756731/187576)
* Attach a non-working ethernet device
* Start the machine (the VM)
* Type the LUKS password on the console 
* See the infinite loop
